pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'DZ_furnace-optimizer', 
                     url: 'https://github.com/VladislavLavrov/423901_devops_SuvorovOleg.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('App_home/furnace_optimizer') {
                    sh 'docker build -t furnace_app .'
                }
            }
        }

        stage('Compose Up') {
            steps {
                dir('App_home/furnace_optimizer') {
                    sh 'docker compose up -d --build'
                }
            }
        }
    }

    post {
        failure {
            echo "❌ Сборка завершилась с ошибкой!"
        }
        success {
            echo "✅ Сборка успешно завершена!"
        }
    }
}