pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy') {
            steps {
                dir('App_home/furnace_optimizer') {
                    sh 'docker compose down || true'
                    sh 'docker compose build --no-cache'
                    sh 'docker compose up -d'
                }
            }
        }
    }
}
