// <auto-generated />
using Calculator_16.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator_16.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    [Migration("20251111082942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Calculator_16.Data.DataInputVariant", b =>
                {
                    b.Property<int>("ID_DataInputVariant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DataInputVariant"));

                    b.Property<string>("Operand_1")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Operand_2")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Result")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Type_operation")
                        .HasColumnType("varchar(128)");

                    b.HasKey("ID_DataInputVariant");

                    b.ToTable("DataInputVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
